// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIoJ-uY79BtqM8nMkd4RfhzoQ_xqdDExY',
    appId: '1:1063038096342:web:266a3ff8d932c63db40a77',
    messagingSenderId: '1063038096342',
    projectId: 'cchess-dev',
    authDomain: 'cchess-dev.firebaseapp.com',
    storageBucket: 'cchess-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJWRoknAwnPdLgzHxsRpcBwLqKgFn0nc',
    appId: '1:1063038096342:android:69cf10a32b5623d9b40a77',
    messagingSenderId: '1063038096342',
    projectId: 'cchess-dev',
    storageBucket: 'cchess-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkokpO_pD0OSFHsajsXXAEJfyt8AvVH8A',
    appId: '1:1063038096342:ios:e60cd5f0607d55f2b40a77',
    messagingSenderId: '1063038096342',
    projectId: 'cchess-dev',
    storageBucket: 'cchess-dev.firebasestorage.app',
    iosBundleId: 'vn.cchess.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkokpO_pD0OSFHsajsXXAEJfyt8AvVH8A',
    appId: '1:1063038096342:ios:e60cd5f0607d55f2b40a77',
    messagingSenderId: '1063038096342',
    projectId: 'cchess-dev',
    storageBucket: 'cchess-dev.firebasestorage.app',
    iosBundleId: 'vn.cchess.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIoJ-uY79BtqM8nMkd4RfhzoQ_xqdDExY',
    appId: '1:1063038096342:web:282047bd96997f59b40a77',
    messagingSenderId: '1063038096342',
    projectId: 'cchess-dev',
    authDomain: 'cchess-dev.firebaseapp.com',
    storageBucket: 'cchess-dev.firebasestorage.app',
  );
}
